const lessonTitle = "借车";

const lessonData = [
    // 正文第 1 段
    ["这是", "zhè shì", "This is", "Ini adalah"],
    ["三十多年前", "sān shí duō nián qián", "more than thirty years ago", "lebih tiga puluh tahun yang lalu"],
    ["的", "de", "particle", ""],
    ["一个", "yí gè", "a", "sebuah / satu"],
    ["故事", "gù shi", "story", "cerita / kisah"],
    ["。", "", "", ""],
    ["徐家村", "xú jiā cūn", "Xu Family Village", "Kampung Keluarga Xu"],
    ["有户", "yǒu hù", "has a (family)", "ada seisi / sebuah"],
    ["人家", "rén jiā", "family", "keluarga"],
    ["叫", "jiào", "called / named", "bernama"],
    ["徐方仁", "xú fāng rén", "Xu Fangren (Name)", "Xu Fangren"],
    ["，", "", "", ""],
    ["家里", "jiā lǐ", "at home / family", "dalam rumah / keluarga"],
    ["环境", "huán jìng", "financial condition / environment", "keadaan / situasi ekonomi"],
    ["不错", "bú cuò", "not bad / quite good", "tidak menghampakan / agak baik"],
    ["。", "", "", ""],
    ["那个年代", "nà gè nián dài", "in those days / that era", "pada zaman itu"],
    ["如果", "rú guǒ", "if", "jika / kalau"],
    ["有人家", "yǒu rén jiā", "any family", "ada keluarga"],
    ["可以", "kě yǐ", "could", "boleh / mampu"],
    ["买", "mǎi", "buy", "membeli"],
    ["一辆", "yí liàng", "a (measure word for vehicle)", "sebuah"],
    ["凤凰牌", "fèng huáng pái", "Phoenix brand", "Jenama Phoenix"],
    ["自行车", "zì xíng chē", "bicycle", "basikal"],
    ["，", "", "", ""],
    ["那就", "nà jiù", "then it", "maka ia akan"],
    ["成了", "chéng le", "became", "menjadi"],
    ["村里", "cūn lǐ", "in the village", "dalam kampung"],
    ["爆炸性的", "bào zhà xìng de", "explosive / sensational", "sensasi / gempar"],
    ["新闻", "xīn wén", "news", "berita"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 2 段

    ["徐方仁家", "xú fāng rén jiā", "Xu Fangren's family", "Keluarga Xu Fangren"],
    ["就", "jiù", "exactly / just", "pun"],
    ["买了一辆", "mǎi le yí liàng", "bought a", "membeli sebuah"],
    ["凤凰牌", "fèng huáng pái", "Phoenix brand", "Jenama Phoenix"],
    ["自行车", "zì xíng chē", "bicycle", "basikal"],
    ["。", "", "", ""],
    ["当他", "dāng tā", "when he", "Apabila dia"],
    ["把", "bǎ", "structural particle", ""],
    ["自行车", "zì xíng chē", "bicycle", "basikal itu"],
    ["骑回来", "qí huí lái", "rode back", "menunggang pulang"],
    ["时", "shí", "when", "apabila / ketika"],
    ["，", "", "", ""],
    ["村民们", "cūn mín men", "villagers", "orang-orang kampung / penduduk"],
    ["前呼后拥", "qián hū hòu yōng", "crowding around", "berduyung-duyung mengelilingi / mengerumuni"],
    ["来看", "lái kàn", "came to look at", "datang melihat"],
    ["他的", "tā de", "his", "dia punya"],
    ["车子", "chē zi", "vehicle / bicycle", "basikal / kereta"],
    ["。", "", "", ""],
    ["他们", "tā men", "they", "Mereka"],
    ["看着", "kàn zhe", "looking at", "melihat / menatap"],
    ["那", "nà", "that", "yang"],
    ["刷亮刷亮的", "shuà liàng shuà liàng de", "shiny / glittering", "berkilat-kilat / sangat berkilau"],
    ["车子", "chē zi", "bicycle", "basikal itu"],
    ["，", "", "", ""],
    ["个个", "gè gè", "everyone", "masing-masing / semua orang"],
    ["都", "dōu", "all", "pun"],
    ["夸他", "kuā tā", "praised him", "memuji dia"],
    ["有钱", "yǒu qián", "wealthy / rich", "kaya / berada"],
    ["，", "", "", ""],
    ["徐方仁", "xú fāng rén", "Xu Fangren", "Xu Fangren"],
    ["也", "yě", "also", "juga / turut"],
    ["因此", "yīn cǐ", "because of this", "oleh sebab itu / maka"],
    ["脸上有光", "liǎn shàng yǒu guāng", "felt proud", "berasa bangga / mendapat nama / megah"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 3 段

    ["自从", "zì cóng", "since", "Semenjak / sejak"],
    ["有了", "yǒu le", "had / possessed", "mempunyai"],
    ["这辆", "zhè liàng", "this", "sebuah ini punya"],
    ["车子", "chē zi", "bicycle", "basikal"],
    ["后", "hòu", "after", "selepas"],
    ["，", "", "", ""],
    ["徐方仁", "xú fāng rén", "Xu Fangren", "Xu Fangren"],
    ["把它", "bǎ tā", "it (object particle)", "membawanya / menganggapnya"],
    ["当作", "dàng zuò", "treat as", "sebagai"],
    ["宝贝", "bǎo bèi", "treasure / baby", "harta kesayangan / khazanah"],
    ["一样", "yí yàng", "the same as", "sedemikian / bagaikan"],
    ["来爱护", "lái ài hù", "to cherish / protect", "untuk disayangi dan dijaga"],
    ["。", "", "", ""],
    ["每次", "měi cì", "every time", "Setiap kali"],
    ["骑过", "qí guò", "rode", "selepas menunggang"],
    ["之后", "hòu", "after", "selepas"],
    ["，", "", "", ""],
    ["自行车", "zì xíng chē", "bicycle", "basikal itu"],
    ["都要", "dōu yào", "must always", "pasti akan"],
    ["洗得", "xǐ de", "washed (with description)", "dicuci sehingga"],
    ["干干净净", "gān gān jìng jìng", "spotlessly clean", "bersih-sebersihnya"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["用干布", "yòng gān bù", "use dry cloth", "menggunakan kain kering"],
    ["擦得", "cā de", "wiped until", "mengesat sehingga"],
    ["亮闪闪的", "liàng shǎn shǎn de", "sparkling / shiny", "berkilau-kilau"],
    ["。", "", "", ""],
    ["村里", "cūn lǐ", "in the village", "Dans kampung punya"],
    ["同他", "tóng tā", "with him", "dengan dia"],
    ["最要好的", "zuì yào hǎo de", "the best (friend)", "paling rapat punya"],
    ["朋友", "péng you", "friend", "kawan"],
    ["，", "", "", ""],
    ["想借", "xiǎng jiè", "want to borrow", "mahu meminjam"],
    ["它的", "tā de", "his", "dia punya"],
    ["车子", "chē zi", "bicycle", "basikal"],
    ["过过瘾", "guò guò yǐn", "satisfy a craving", "merasa seronok menunggang / melepaskan gian"],
    ["，", "", "", ""],
    ["他都", "tā dōu", "he all", "dia semua"],
    ["不同意", "bù tóng yì", "disagree / refuse", "tidak bersetuju / enggan"],
    ["。", "", "", ""],
    ["连他", "lián tā", "even his", "Bahkan anak lelaki"],
    ["儿子", "ér zi", "son", "dia sendiri"],
    ["想学", "xiǎng xué", "want to learn", "mahu belajar"],
    ["骑自行车", "qí zì xíng chē", "ride bicycle", "menunggang basikal"],
    ["，", "", "", ""],
    ["他也是", "tā yě shì", "he also was", "dia pun tetap"],
    ["不同意", "bù tóng yì", "refuse / disagree", "tidak membenarkan / enggan"],
    ["，", "", "", ""],
    ["担心", "dān xīn", "worry", "bimbang / risau"],
    ["把它", "bǎ tā", "object particle (his)", "akan"],
    ["车子", "chē zi", "bicycle", "basikal dia"],
    ["骑坏了", "qí huài le", "broken by riding", "ditunggang sampai rosak"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 4 段

    ["一个", "yí gè", "A", "Seorang"],
    ["名叫", "míng jiào", "named", "bernama"],
    ["李笑中的", "lǐ xiào zhōng de", "Li Xiaozhong's", "Li Xiaozhong"],
    ["河南人", "hé nán rén", "Henan person", "orang Henan"],
    ["，", "", "", ""],
    ["挑炭", "tiāo tàn", "carrying charcoal on shoulder pole", "memikul arang"],
    ["到处", "dào chù", "everywhere", "ke sana ke mari / merata-rata"],
    ["叫卖", "jiào mài", "hawking / peddling", "menjajanya / melaung jualan"],
    ["。", "", "", ""],
    ["路过", "lù guò", "pass by", "Ketika lalu / melintasi"],
    ["徐家村", "xú jiā cūn", "Xu Family Village", "Kampung Keluarga Xu"],
    ["时", "shí", "when", "waktu"],
    ["，", "", "", ""],
    ["找他", "zhǎo tā", "approach him for", "menemui dia untuk meminta"],
    ["茶喝", "chá hē", "tea to drink", "air teh minum"],
    ["。", "", "", ""],
    ["李笑中", "lǐ xiào zhōng", "Li Xiaozhong", "Li Xiaozhong"],
    ["是一个", "shì yí gè", "was a", "adalah seorang"],
    ["老江湖", "lǎo jiāng hú", "old hand", "orang yang lama makan garam / berpengalaman luas"],
    ["，", "", "", ""],
    ["见人", "jiàn rén", "meet people", "bila jumpa orang"],
    ["甜言蜜语", "tián yán mǐ yǔ", "sweet words / honeyed words", "pandai manis mulut / kata-kata manis"],
    ["，", "", "", ""],
    ["吹捧得", "chuī pěng de", "flattering until", "mengampu / membodek sehingga"],
    ["徐方仁", "xú fāng rén", "Xu Fangren", "Xu Fangren"],
    ["五迷三道的", "wǔ mí sān dào de", "completely infatuated / dazed", "menjadi khayal / terbuai-buai / kembang hidung"],
    ["。", "", "", ""],
    ["他还", "tā hái", "he also", "Dia juga"],
    ["大哥长", "dà gē cháng", "brother long", "panggil abang sana"],
    ["大哥短", "dà gē duǎn", "brother short", "panggil abang sini"],
    ["，", "", "", ""],
    ["就像是", "jiù xiàng shì", "just resembles", "bagaikan / seolah-olah"],
    ["老朋友", "lǎo péng you", "old friend", "kawan lama"],
    ["一样", "yí yàng", "the same", "sedemikian"],
    ["那么亲热", "nà me qīn rè", "so affectionate / warm", "begitu mesra sekali"],
    ["。", "", "", ""],
    ["就这样", "jiù zhè yàng", "Just like this", "Dengan cara begini"],
    ["李笑中", "lǐ xiào zhōng", "Li Xiaozhong", "Li Xiaozhong"],
    ["每次", "měi cì", "every time", "setiap kali"],
    ["路过", "lù guò", "passing by", "lalu menziarahi"],
    ["徐家村", "xú jiā cūn", "Xu Family Village", "Kampung Keluarga Xu"],
    ["时", "shí", "when", "ketika"],
    ["，", "", "", ""],
    ["都要到", "dōu yào dào", "must go to", "pasti akan ke"],
    ["徐方仁", "xú fāng rén", "Xu Fangren's", "Xu Fangren punya"],
    ["家里", "jiā lǐ", "home", "rumah"],
    ["坐坐", "zuò zuo", "sit for a bit", "duduk berbual"],
    ["。", "", "", ""],
    ["有时候", "yǒu shí hou", "Sometimes", "Kadang-kala"],
    ["一坐就", "yí zuò jiù", "once sit then", "sekali duduk terus"],
    ["老半天", "lǎo bàn tiān", "a long time / half a day", "lama sekali / separuh hari"],
    ["，", "", "", ""],
    ["遇上", "yù shàng", "encounter / happen to be", "kebetulan masa"],
    ["吃午饭", "chī wǔ fàn", "eat lunch", "makan tengah hari"],
    ["时", "shí", "when", "waktu"],
    ["，", "", "", ""],
    ["李笑中", "lǐ xiào zhōng", "Li Xiaozhong", "Li Xiaozhong"],
    ["就在他家", "jiù zài tā jiā", "just at his home", "terus di rumah dia"],
    ["吃饭", "chī fàn", "eat meal", "makan nasi"],
    ["。", "", "", ""],
    ["吃完饭", "chī wán fàn", "after finishing meal", "Selesai makan"],
    ["后", "hòu", "after", "selepas itu"],
    ["，", "", "", ""],
    ["笑呵呵地", "xiào hē hē de", "smilingly", "sambil tersenyum riang"],
    ["拍拍屁股", "pāi pāi pì gǔ", "pat buttocks", "menepuk-nepuk punggung (konteks: terus bangun)"],
    ["就走了", "jiù zǒu le", "then left", "dan pergi"],
    ["。", "", "", ""],
    ["第二次", "dì èr cì", "The second time", "Kali kedua"],
    ["来时", "lái shí", "when coming", "datang nanti"],
    ["，", "", "", ""],
    ["李笑中", "lǐ xiào zhōng", "Li Xiaozhong", "Li Xiaozhong"],
    ["就带上", "jiù dài shàng", "then brought along", "pasti membawa bersama"],
    ["一挂肉", "yí guà ròu", "a string of meat", "setongkol daging / seuntai daging"],
    ["来", "lái", "come", "datang"],
    ["。", "", "", ""],
    ["稳妥", "zhè yàng", "Like this", "Dengan cara begini"],
    ["一来二往", "yì lái èr wǎng", "social dealings", "lama-kelamaan saling berkunjung"],
    ["，", "", "", ""],
    ["时间长了", "shí jiān cháng le", "as time passed by", "apabila masa berlanjutan lama"],
    ["，", "", "", ""],
    ["两个", "liǎng gè", "the two of them", "kedua-dua orang itu"],
    ["好得", "hǎo de", "good until", "menjadi rapat sehingga"],
    ["就像", "jiù xiàng", "just like", "bagaikan"],
    ["亲兄弟", "qīn xiōng dì", "biological brothers", "saudara kandung"],
    ["一样", "yí yàng", "the same", "sendiri"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 5 段
    ["一天", "yì tiān", "One day", "Pada suatu hari"],
    ["，", "", "", ""],
    ["李笑中", "lǐ xiào zhōng", "Li Xiaozhong", "Li Xiaozhong"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["大哥", "dà gē", "Big Brother", "Abang"],
    ["，", "", "", ""],
    ["我今天", "wǒ jīn tiān", "I today", "saya hari ini"],
    ["有点", "yǒu diǎn", "have a bit", "ada sedikit"],
    ["急事", "jí shì", "urgent matter", "perkara cemas / urusan penting"],
    ["，", "", "", ""],
    ["这里", "zhè lǐ", "here", "di sini"],
    ["又没有", "yòu méi yǒu", "also does not have", "pula tidak ada"],
    ["顺便车", "shùn biàn chē", "hitchhiking ride", "kenderaan tumpang / bas awam"],
    ["，", "", "", ""],
    ["想借", "xiǎng jiè", "want to borrow", "mahu meminjam"],
    ["你的", "tā de", "your", "abang punya"],
    ["车子", "chē zi", "bicycle", "basikal"],
    ["骑一骑", "qí yì qí", "ride a bit", "untuk tunggang sekejap"],
    ["，", "", "", ""],
    ["两个小时", "liǎng gè xiǎo shí", "two hours", "dua jam"],
    ["后", "hòu", "later", "kemudian"],
    ["，", "", "", ""],
    ["我就", "wǒ jiù", "I then", "saya pasti akan"],
    ["还给你", "huán gěi nǐ", "return to you", "pulangkan balik kepada abang"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 6 段
    ["徐方仁", "xú fāng rén", "Xu Fangren", "Xu Fangren"],
    ["听了", "tīng le", "heard", "mendengar"],
    ["李笑中的", "lǐ xiào zhōng de", "Li Xiaozhong's", "Li Xiaozhong punya"],
    ["话", "huà", "words", "kata-kata"],
    ["，", "", "", ""],
    ["半天", "bàn tiān", "half a day / long time", "lama sekali"],
    ["没有吭声", "méi yǒu kēng shēng", "did not utter a word", "langsung tidak bersuara / membisu"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 7 段
    ["李笑中", "lǐ xiào zhōng", "Li Xiaozhong", "Li Xiaozhong"],
    ["又说", "yòu shuō", "said again", "berkata lagi"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我骑车的", "wǒ qí chē de", "my riding", "Saya punya kemahiran menunggang"],
    ["技术", "jì shù", "technique / skill", "teknik"],
    ["很好的", "hěn hǎo de", "very good", "sangat bagus"],
    ["，", "", "", ""],
    ["won't会", "bú huì", "will not", "tidak akan"],
    ["弄坏", "nòng huài", "break / damage", "merosakkan"],
    ["你的", "tā de", "your", "abang punya"],
    ["车子", "chē zi", "bicycle", "basikal"],
    ["。", "", "", ""],
    ["这样", "zhè yàng", "Like this", "Begini sahaja"],
    ["，", "", "", ""],
    ["我放", "wǒ fàng", "I place", "saya letakkan"],
    ["二百块", "liǎng bǎi kuài", "two hundred dollars", "dua ratus ringgit"],
    ["在你这里", "zài nǐ zhè lǐ", "here with you", "di tempat abang"],
    ["，", "", "", ""],
    ["如果", "rú guǒ", "if", "kalau / sekiranya"],
    ["把你", "bǎ nǐ", "object particle (your)", "menyebabkan abang punya"],
    ["车子", "chē zi", "bicycle", "basikal"],
    ["搞坏了", "gǎo huài le", "broken / damaged", "rosak"],
    ["，", "", "", ""],
    ["这钱", "zhè qián", "this money", "wang ini"],
    ["我就", "wǒ jiù", "I then", "saya terus"],
    ["不要了", "bú yào le", "do not want anymore", "tidak mahu balik"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["说完", "shuō wán", "finished speaking", "Selesai berkata"],
    ["从口袋里", "cóng kǒu dài lǐ", "from inside the pocket", "dari dalam saku baju"],
    ["掏出", "tāo chū", "pulled out", "menyeluk keluar"],
    ["二百块", "liǎng bǎi kuài", "two hundred dollars", "dua ratus ringgit"],
    ["，", "", "", ""],
    ["塞在", "sāi zài", "stuffed into", "menyelitkan ke dalam / menggenggam ke"],
    ["徐方仁的", "xú fāng rén de", "Xu Fangren's", "Xu Fangren punya"],
    ["手里", "shǒu lǐ", "hand", "tangan"],
    ["。", "", "", ""],
    ["徐方仁", "xú fāng rén", "Xu Fangren", "Xu Fangren"],
    ["就把车", "jiù bǎ chē", "then gave the bicycle", "lalu menyerahkan basikal"],
    ["给了他", "gěi le tā", "to him", "kepada dia"],
    ["，", "", "", ""],
    ["还是", "hái 】", "still", "namun tetap juga"],
    ["嘱妇他", "zhǔ fù tā", "reminded him", "berpesan kepada dia"],
    ["一定", "yí dìng", "definitely", "pasti / wajib"],
    ["好好", "hǎo hǎo", "carefully", "elok-elok / baik-baik"],
    ["爱惜", "ài xī", "cherish", "menyayangi dan menjaga"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 8 段
    ["徐方仁", "xú fāng rén", "Xu Fangren", "Xu Fangren"],
    ["这是", "zhè shì", "this was", "ini adalah"],
    ["第一次", "dì yī cì", "the first time", "kali pertama"],
    ["把车", "bǎ chē", "the bicycle", "menyerahkan basikal"],
    ["借给别人", "jiè gěi bié rèn", "lend to others", "pinjam kepada orang lain"],
    ["，", "", "", ""],
    ["心里", "xīn lǐ", "in the heart", "dalam hati"],
    ["难免", "nán miǎn", "unavoidably", "tidak dapat dielakkan / sudah tentu berasa"],
    ["有些", "yǒu xiē", "a bit", "sedikit perasaan"],
    ["七上八下", "qī shàng bā xià", "perturbed / anxious", "berdebar-debar / gelisah / tidak menentu"],
    ["，", "", "", ""],
    ["最担心", "zuì dān xīn", "most worried", "paling risau kalau-kalau"],
    ["他把", "bǎ tā", "he object particle", "dia menyebabkan"],
    ["车子", "chē zi", "bicycle", "basikal itu"],
    ["骑坏了", "qí huài le", "broken by riding", "ditunggang sampai rosak"],
    ["。", "", "", ""],
    ["太阳落山", "tài yáng luò shān", "sunset", "Matahari terbenam / senja"],
    ["时", "shí", "when", "apabila"],
    ["，", "", "", ""],
    ["李笑中", "lǐ xiào zhōng", "Li Xiaozhong", "Li Xiaozhong"],
    ["把车子", "bǎ chē zi", "the bicycle", "basikal itu"],
    ["完好无损地", "wán hǎo wú sǔn de", "intact and undamaged", "dalam keadaan yang sempurna tanpa sebarang kerosakan"],
    ["骑了", "qí le", "rode", "telah tunggang"],
    ["回来了", "huí lái le", "back", "pulang"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 9 段
    ["徐方仁", "xú fāng rén", "Xu Fangren", "Xu Fangren"],
    ["把钱", "bǎ qián", "the money", "wang itu"],
    ["退给了", "tuì gěi le", "returned to", "memulangkan balik kepada"],
    ["李笑中", "lǐ xiào zhōng", "Li Xiaozhong", "Li Xiaozhong"],
    ["，", "", "", ""],
    ["李笑中", "lǐ xiào zhōng", "Li Xiaozhong", "Li Xiaozhong"],
    ["依然", "yī rán", "still / as before", "tetap / masih"],
    ["强塞钱", "qiáng sāi qián", "forcefully stuffed money", "memaksa serah wang / menyumbat keras wang"],
    ["到他", "dào tā", "into his", "ke dalam dia punya"],
    ["手里", "shǒu lǐ", "hand", "tangan"],
    ["说", "shuō", "said", "dan berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你今天", "nǐ jīn tiān", "you today", "Abang hari ini"],
    ["帮了", "bāng le", "helped", "telah membantu"],
    ["我大忙", "wǒ dà máng", "me a big favor", "saya urusan yang teramat besar"],
    ["，", "", "", ""],
    ["不是你的", "bú shì nǐ de", "if it wasn't for your", "kalau bukan kerana abang punya"],
    ["车子", "chē zi", "bicycle", "basikal"],
    ["，", "", "", ""],
    ["我今天", "wǒ jīn tiān", "I today", "saya hari ini"],
    ["赶不回来", "gǎn bù huí lái", "could not rush back", "tidak sempat kejar pulang"],
    ["。", "", "", ""],
    ["谢谢你", "xiè xie nǐ", "thank you", "Terima kasih abang"],
    ["处理", "", "", ""],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 10 段
    ["徐方仁", "xú fāng rén", "Xu Fangren", "Xu Fangren"],
    ["心里", "xīn lǐ", "in the heart", "dalam hati"],
    ["高兴", "gāo xìng", "happy / glad", "berasa sangat gembira"],
    ["。", "", "", ""],
    ["这个", "zhè ge", "this", "Ini punya"],
    ["朋友", "péng you", "friend", "kawan"],
    ["没有白交", "méi yǒu bái jiāo", "not made in vain", "tidak sia-sia berkawan"],
    ["，", "", "", ""],
    ["真是一个", "zhēn shì yí gè", "really is a", "sungguh merupakan seorang"],
    ["有情有义的", "yǒu qíng yǒu yì de", "affectionate and righteous", "yang setia dan penuh amanah / berbudi"],
    ["人", "rén", "person", "manusia"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 11 段
    ["时间", "shí jiān", "Time", "Masa"],
    ["又过去", "guò qù le", "passed by again", "pula berlalu"],
    ["半年", "bàn nián", "half a year", "setengah tahun"],
    ["。", "", "", ""],
    ["那是一个", "nà shì yí gè", "That was a", "Ia merupakan suatu"],
    ["冬天的", "dōng tiān de", "winter's", "musim sejuk punya"],
    ["早上", "zǎo chen", "morning", "pagi"],
    ["，", "", "", ""],
    ["李笑中", "lǐ xiào zhōng", "Li Xiaozhong", "Li Xiaozhong"],
    ["来了", "lái le", "came / arrived", "telah datang menziarahi"],
    ["。", "", "", ""],
    ["他", "tā", "he", "Dia"],
    ["笑呵呵地", "xiào hē hē de", "smilingly", "sambil tersenyum riang"],
    ["叫道", "jiào dào", "called out", "melaung panggil"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["大哥", "dà gē", "Big Brother", "Abang"],
    ["，", "", "", ""],
    ["我今天", "wǒ jīn tiān", "I today", "saya hari ini"],
    ["还想", "hái xiǎng", "still want to", "masih mahu"],
    ["借你的", "jiè nǐ de", "borrow your", "pinjam abang punya"],
    ["车子", "chē zi", "bicycle", "basikal"],
    ["用一用", "yòng yí yòng", "use a bit", "guna sekejap"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 12 段
    ["徐方仁", "xú fāng rén", "Xu Fangren", "Xu Fangren"],
    ["爽快地", "shuǎng kuài de", "readily", "dengan senang hati / tanpa ragu-ragu"],
    ["答应了", "dā yìng le", "agreed / promised", "bersetuju membenarkan"],
    ["，", "", "", ""],
    ["又问", "yòu wèn", "asked again", "pula bertanya"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你", "nǐ", "you", "kamu"],
    ["什么时候", "shén me shí hou", "what time / when", "pukul berapa / bila"],
    ["回来", "huí lái", "return", "pulang ke sini"],
    ["，", "", "", ""],
    ["下午", "xià wǔ", "afternoon", "petang nanti"],
    ["我自己", "wǒ zì jǐ", "I myself", "saya sendiri"],
    ["也要用", "yě yào yòng", "also need to use", "pun nak guna"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 13 段
    ["“", "", "", ""],
    ["上午", "shàng wǔ", "In the morning", "Sebelum tengah hari / pagi ini"],
    ["我就可以", "wǒ jiù kě yǐ", "I then can", "saya sudah boleh"],
    ["回来", "huí lái", "return", "pulang"],
    ["，", "", "", ""],
    ["不耽误", "bù dān wu", "won't delay", "tidak akan melengah-lengahkan masa / mengganggu"],
    ["你的事", "nǐ de shì", "your business", "abang punya urusan"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["他", "tā", "he", "Dia"],
    ["边说边摸", "biān shuō biān mō", "fumbled whilst speaking", "sambil bercakap sambil menyeluk raba"],
    ["自己", "zì jǐ", "one's own", "diri sendiri punya"],
    ["口袋", "kǒu dài", "pocket", "saku baju / kocek"],
    ["，", "", "", ""],
    ["摸了半天", "mō le bàn tiān", "fumbled for a long time", "meraba lama sekali"],
    ["，", "", "", ""],
    ["却说", "què shuō", "but said", "sebaliknya berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["大哥", "dà gē", "Big Brother", "Abang"],
    ["，", "", "", ""],
    ["车子", "chē zi", "bicycle", "basikal itu"],
    ["我借不了了", "wǒ jiè bù liǎo le", "I cannot borrow anymore", "saya tidak boleh pinjamlah"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 14 段
    ["“", "", "", ""],
    ["怎么啦", "zěn me la", "What's wrong", "Kenapa pula"],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 15 段
    ["“", "", "", ""],
    ["我今天", "wǒ jīn tiān", "I today", "Saya hari ini"],
    ["走得匆忙", "zǒu de cōng máng", "left in a hurry", "berjalan dengan tergesa-gesa / kalut"],
    ["，", "", "", ""],
    ["忘记带钱", "wàng jì dài qián", "forgot to bring money", "terlupa membawa wang cagaran"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["他说完", "tā shuō wán", "He finished speaking", "Selesai bercakap dia"],
    ["抓了抓头", "zhuā le zhuā tóu", "scratched his head", "menggaru-garu kepala"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 16 段
    ["徐方仁", "xú fāng rén", "Xu Fangren", "Xu Fangren"],
    ["笑了笑", "xiào le xiào", "smiled", "tersenyum sedikit lalu"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["想借", "xiǎng jiè", "want to borrow", "Kalau mahu pinjam"],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "kamu"],
    ["就拿去吧", "jiù ná qù ba", "just take it", "ambil sahajalah menghala"],
    ["！", "", "", ""],
    ["我们是", "wǒ men shì", "we are", "Kita adalah"],
    ["朋友", "péng you", "friends", "kawan rapat"],
    ["，", "", "", ""],
    ["你总不至于", "nǐ zǒng bú zhì yú", "surely you won't", "kamu masakan sampai hati / takkanlah pula"],
    ["骗我", "piàn wǒ", "cheat me", "menipu saya"],
    ["一部", "yí bù", "a (measure word for vehicle)", "sebuah"],
    ["车子吧", "chē zi ba", "bicycle", "basikal kan"],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 17 段
    ["“", "", "", ""],
    ["大哥", "dà gē", "Big Brother", "Abang"],
    ["，", "", "", ""],
    ["我们也", "wǒ men yě", "we also", "kita pun"],
    ["认识", "rèn shi", "known each other", "telah kenal"],
    ["这么久了", "zhè me jiǔ le", "for so long", "begitu lama sekali"],
    ["，", "", "", ""],
    ["我是", "wǒ shì", "I am", "saya adalah"],
    ["什么人", "shén me rén", "what kind of person", "manusia jenis apa"],
    ["你还不", "nǐ hái bù", "you still not", "abang masih belum"],
    ["了解吗", "liǎo jiě ma", "understand", "paham kah"],
    ["？", "", "", ""],
    ["大哥你", "dà gē nǐ", "Big Brother you", "Abang begitu"],
    ["对我这么好", "duì wǒ zhè me hǎo", "treat me so well", "baik terhadap saya"],
    ["，", "", "", ""],
    ["如果我要", "rú guǒ wǒ yào", "if I want to", "sekiranya saya berniat"],
    ["骗你的", "piàn nǐ de", "cheat your", "menipu abang punya"],
    ["车子", "chē zi", "bicycle", "basikal"],
    ["，", "", "", ""],
    ["我还是人吗", "wǒ hái )))", "am I still human", "adakah saya ini masih manusia lagi"],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 18 段
    ["徐方仁", "xú fāng rén", "Xu Fangren", "Xu Fangren"],
    ["拍了拍", "pāi le pāi", "patted", "menepuk-nepuk"],
    ["他的", "tā de", "his", "dia punya"],
    ["肩膀", "jiān bǎng", "shoulder", "bahu"],
    ["说", "shuō", "said", "dan berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["知道了", "zhī dào le", "Understood", "Dah tahu / baiklah"],
    ["，", "", "", ""],
    ["你把车子", "nǐ bǎ chē zi", "you the bicycle", "kamu bawalah basikal itu"],
    ["骑去吧", "qí qù ba", "ride it away", "pergi tunggang"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 19 段
    ["李笑中", "lǐ xiào zhōng", "Li Xiaozhong", "Li Xiaozhong"],
    ["从容不迫地", "cóng róng bú pò de", "calmly and unhurriedly", "dengan tenang tanpa sebarang gopoh-gapan"],
    ["把车子", "bǎ chē zi", "the bicycle", "membawa basikal itu"],
    ["骑过来", "qí guò lái", "ride over", "menghala ke mari"],
    ["，", "", "", ""],
    ["捏捏", "niē nie", "pinched", "memicit-micit"],
    ["车胎", "chē tāi", "tyre", "tayar basikal"],
    ["，", "", "", ""],
    ["有没有气", "yǒu méi yǒu qì", "whether there is air", "ada angin atau tidak"],
    ["。", "", "", ""],
    ["然后", "rán hòu", "Then", "Kemudian"],
    ["把车子", "bǎ chē zi", "the bicycle", "membawa basikal itu"],
    ["推到", "tuī dào", "pushed to", "menolak ke"],
    ["外面", "wài mian", "outside", "luar"],
    ["，", "", "", ""],
    ["左脚", "zuǒ jiǎo", "left foot", "kaki kiri"],
    ["踩在", "cǎi zài", "stepped on", "memijak atas"],
    ["脚踏上", "jiǎo tà shàng", "pedal", "pengayuh basikal"],
    ["，", "", "", ""],
    ["右脚", "yòu jiǎo", "right foot", "kaki kanan"],
    ["一抬", "yì tái", "once lifted", "diangkat sahaja terus"],
    ["就上去了", "jiù shàng qù le", "then went up", "naik ke atas basikal"],
    ["，", "", "", ""],
    ["车子", "chē zi", "bicycle", "basikal itu"],
    ["载着他", "zài zhe tā", "carrying him", "membawa dia bersama"],
    ["溜溜地", "liū liū de", "smoothly", "meluncur laju dengan"],
    ["跑了", "pǎo le", "sped off", "pergi / bergerak jauh"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 20 段
    ["徐方仁", "xú fāng rén", "Xu Fangren", "Xu Fangren"],
    ["等到", "děng dào", "waited until", "menunggu sehingga"],
    ["中午", "zhōng wǔ", "noon", "tengah hari"],
    ["时", "shí", "when", "waktu"],
    ["，", "", "", ""],
    ["还不见", "hái bú jiàn", "still did not see", "masih tidak kelihat kelibat"],
    ["李笑中", "lǐ xiào zhōng", "Li Xiaozhong", "Li Xiaozhong"],
    ["回来", "huí lái", "return", "pulang"],
    ["。", "", "", ""],
    ["他心里想", "tā xīn lǐ xiǎng", "He thought in his heart", "Dia berfikir dalam hati"],
    ["，", "", "", ""],
    ["是不是", "shì bú shì", "whether or not", "adakah / sama ada mungkin"],
    ["在路上", "zài lù shàng", "on the road", "di tengah jalan"],
    ["出了一点", "chū le yì diǎn", "happened a bit of", "mengalami sedikit"],
    ["意外", "yì wài", "accident / mishap", "kemalangan / masalah"],
    ["？", "", "", ""],
    ["那个年代", "nà gè nián dài", "in those days", "Pada zaman itu"],
    ["½有手机", "méi yǒu shǒu jī", "no mobile phones", "tidak ada telefon bimbit"],
    ["，", "", "", ""],
    ["又无法", "yòu wú fǎ", "and also no way to", "pula mustahil untuk"],
    ["打电话", "dǎ diàn huà", "make phone calls", "membuat panggilan telefon"],
    ["，", "", "", ""],
    ["他只好", "tā zhǐ hǎo", "he had no choice but to", "dia terpaksa mahu tidak mahu"],
    ["耐心地", "nài xīn de", "patiently", "dengan sabar"],
    ["等待", "děng dài", "wait", "menunggu"],
    ["。", "", "", ""],
    ["可是", "kě shì", "However", "Namun begitu"],
    ["到", "dào", "until", "menjelang waktu"],
    ["太阳西下", "tài yáng xī xià", "sunset", "matahari terbenam"],
    ["了", "le", "particle", ""],
    ["，", "", "", ""],
    ["夜幕降临", "yè mù jiàng lín", "night falls", "malam mula melabuhkan tirainya"],
    ["，", "", "", ""],
    ["还是", "hái shì", "still", "tetap / langsung"],
    ["不见他", "bú jiàn tā", "did not see him", "tidak kelihatan dia"],
    ["回来", "huí lái", "return", "pulang"],
    ["。", "", "", ""],
    ["这下他", "zhè xià tā", "This time he", "Kali ini dia terus"],
    ["心慌意乱", "xīn huāng yì luàn", "flustered / panicked", "menjadi cemas / sangat gelisah hati"],
    ["，", "", "", ""],
    ["他老婆", "tā lǎo pó", "his wife", "isteri dia pula"],
    ["又", "yòu", "again", "asyik"],
    ["叨叨咕咕", "dāo dāo gū gū", "muttering / grumbling", "membebel-bebel / merungut tanpa henti"],
    ["，", "", "", ""],
    ["说", "shuō", "saying", "dan berkata"],
    ["这下好了", "zhè xià hǎo le", "this time fine (sarcastic)", "hah sekarang padan muka / dah elok sangatlah tu"],
    ["，", "", "", ""],
    ["你心爱", "nǐ xīn ài", "your beloved", "kamu punya kesayangan"],
    ["宝贝", "bǎo bèi", "treasure", "harta"],
    ["被人骗走了", "bèi rén piàn zǒu le", "cheated away by someone", "telah dilarikan / ditipu orang pergi"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 21 段
    ["徐方仁", "xú fāng rén", "Xu Fangren", "Xu Fangren"],
    ["不敢相信", "bù kǎn xiāng xìn", "refuse to believe", "tidak berani mempercayai"],
    ["这是真的", "zhè shì zhēn de", "this was true", "ini adalah kenyataan"],
    ["，", "", "", ""],
    ["不会吧", "bú huì ba", "no way / unlikely", "takkanlah / biar betul"],
    ["，", "", "", ""],
    ["他不会", "tā bú huì", "he will not", "dia tidak akan"],
    ["骗我的", "piàn wǒ de", "cheat me", "menipu saya punya"],
    ["，", "", "", ""],
    ["肯定是有", "kěn dìng shì yǒu", "definitely there is", "pasti ada / semestinya mempunyai"],
    ["什么事情", "shén me shì qing", "some matters / issues", "apa-apa urusan atau masalah"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 22 段
    ["两天", "liǎng tiān", "Two days", "Dua hari"],
    ["过去了", "guò qù le", "passed by", "telah berlalu"],
    ["，", "", "", ""],
    ["五天", "wǔ tiān", "five days", "lima hari"],
    ["过去了", "guò qù le", "passed by", "telah berlalu"],
    ["。", "", "", ""],
    ["徐方仁", "xú fāng rén", "Xu Fangren", "Xu Fangren"],
    ["坐不住了", "zuò bú zhù le", "could not sit still anymore", "tidak boleh duduk diam lagi"],
    ["，", "", "", ""],
    ["他要", "tā yào", "he wanted to", "dia mahu"],
    ["去找", "qù zhǎo", "go to look for", "pergi mencari"],
    ["李笑中", "lǐ xiào zhōng", "Li Xiaozhong", "Li Xiaozhong"],
    ["，", "", "", ""],
    ["他知道", "tā zhī dào", "he knew", "dia tahu tempat"],
    ["他烧炭的", "tā shāo tàn de", "his charcoal burning's", "dia membakar arang punya"],
    ["地方", "dì fāng", "place", "kawasan"],
    ["。", "", "", ""],
    ["这一天", "zhè yì tiān", "This day", "Pada hari ini"],
    ["，", "", "", ""],
    ["他行步", "tā xíng bù", "he walked on foot", "dia melangkah kaki / berjalan kaki"],
    ["走了十多里地", "zǒu le shí duō lǐ dì", "walked more than ten li", "berjalan lebih sepuluh li jauhnya tanah"],
    ["来到", "lái dào", "arrived at", "sampai ke"],
    ["黄家垴", "huáng jiā nǎo", "Huangjianao (Place)", "Huangjianao"],
    ["，", "", "", ""],
    ["问", "wèn", "asking", "bertanya"],
    ["河南", "hé nán", "Henan", "orang Henan"],
    ["烧炭的人", "shāo tàn de rén", "charcoal burning people", "yang membakar arang"],
    ["在哪里", "zài nǎ lǐ", "where", "berada di mana"],
    ["？", "", "", ""],
    ["别人", "bié rén", "Others", "Orang lain"],
    ["告诉他", "gào su tā", "told him", "memberitahu dia"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["他们", "tā men", "they", "Mereka semua"],
    ["回家", "huí jiā", "home", "pulang ke kampung"],
    ["过年", "guò nián", "celebrate New Year", "untuk menyambut perayaan / raya"],
    ["去了", "qù le", "went", "dah pergi"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 23 段
    ["徐方仁", "xú fāng rén", "Xu Fangren", "Xu Fangren punya"],
    ["心凉了一截", "xīn liáng le yì jié", "deeply disappointed", "hati terus menjadi sangat hampa / tawar hati / kecewa"],
    ["，", "", "", ""],
    ["泪水", "lèi shuǐ", "tears", "air mata"],
    ["模糊了", "mó hu le", "blurred", "mengaburi / berkaca-kaca"],
    ["眼睛", "yǎn jing", "eyes", "pandangan mata"],
    ["。", "", "", ""],
    ["自己", "zì jǐ", "Oneself", "Diri sendiri"],
    ["怎么会", "zěn me huì", "how could", "bagaimana boleh"],
    ["鬼迷心窍", "guǐ mí xīn qiào", "infatuated / possessed", "seolah-olah dipukau / hilang akal sihat / bodoh sangat"],
    ["相信了", "xiāng xìn le", "believed in", "mempercayai"],
    ["他的", "tā de", "his", "dia punya"],
    ["鬼话", "guǐ huà", "lies", "cakap bohong / tipu helah"],
    ["呢", "ne", "particle", "ya"],
    ["？", "", "", ""],
    ["这车", "zhè chē", "this bicycle", "Basikal ini"],
    ["可是", "kě shì", "exactly / emphasis", "sebenarnya adalah hasil"],
    ["老婆", "tā lǎo pó", "wife", "isteri dia"],
    ["养了一年", "yǎng le yì nián", "reared for a year", "memelihara selama setahun punya"],
    ["的", "de", "particle", ""],
    ["一头猪", "yì tóu zhū", "a pig", "seekor babi"],
    ["卖的钱", "mài de qián", "money from selling", "dijual dapat wang"],
    ["买来的", "mǎi lái de", "bought with", "baru dibeli datang"],
    ["。", "", "", ""],
    ["人心叵测啊", "rén xīn pǒ cè ā", "human hearts are unpredictable", "sungguh busuk hati manusia / hati manusia sukar diduga"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 出处
    ["（", "", "", ""],
    ["星光", "xīng guāng", "Xingguang (Author)", "Xingguang (Penulis)"],
    ["《", "", "", ""],
    ["借车", "jiè chē", "Lending the Bicycle", "Meminjam Basikal"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
